spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        healthCheckPath: ${management.contextPath:}/health
        healthCheckInterval: 15s
        instance-id: homecare-v1-consul
  application:
    name: homecare-v1-consul
server:
  port: 8502